<?php
	$array = 
	[
		"viewmoreoption" => "Klik untuk melihat lebih banyak pilihan",
		"viewda" => "Klik untuk Menambah Doer Action",
		"viewcda" => "Klik untuk melihat atau menutup Doer Action",
		"viewkr" => "Klik untuk Menambah Keputusan Utama",
		"viewckr" => "Klik untuk Melihat Sumbang OKR",
		"viewcollapse" => "Klik untuk meruntuhkan atau menunjukkan",
		"committed" => "komited",
		"aspirational" => "Cita Tinggi",
		"toplevel" => "Tahap Teratas",
		"reportsubmit" => "Laporan Telah Hantar",
		"reportnotsubmit" => "Laporan Belum Hantar",
		"reportreview" => "Lapran Telah Ulas",
		"reportnotreview" => "Laporan Belum Ulas",
		"totalobjective" => "Jumlah Objektif",
		"howmany" => "Berapa banyak objektif yang dibuat dalam Tempoh Masa ini",
		"loginrate" => "Kadar Log Masuk",
		"updaterate" => "Kadar Kemas Kini",
		"currentprogress" => "Kemajuan Semasa",
		"togo" => "Yang Tinggal",
		"expected" => "Dijangka",
		"supervisor" => "Penyelia",
		"admin" => "Admin",
		"chief" => "Pemimpin",
		"superior" => "Unggul",
		"manager" => "Pengurus",
		"evaluate" => "Menilai",
		"progressremarks" => "Kata-kata Kemajuan",
		"problemremarks" => "Kata-kata Masalah",
		"nextweekplanremarks" => "Kata-kata Pelan Minggu Depan",
		"problem" => "Masalah",
		"nextweekplan" => "Pelan Minggu Depan",
		"plan" => "Pelan",
		"draft" => "Draf",
		"department" => "Jabatan",
		"team" => "Kumpulan",
		"project" => "Projek",
		"campaign" => "kempen",
		"optional" => "pilihan",
		"active" => "Aktif",
		"notactive" => "Tak Aktif",
		"description" => "Keterangan",
		"marksas" => "Tanda Sebagai ",
		"unit" => "Unit",
		"percentage" => "Peratusan",
		"currency" => "Mata Wang",
		"metric" => "Metrik",
		"startvalue" => "Nilai Mula",
		"endvalue" => "Nilai Akhir",
		"new" => "Baru",
		"okrlogs" => "OKR Logs",
		"alignto" => "Jajarkan",
		"owner" => "Pemilik",
		"overallprogress" => "Kemajuan Keseluruhan",
		"progresstimeline" => "Kemajuan Garis Masa",
		"keyactivity" => "Aktiviti Utama",
		"showkeyactivity" => "Tunjukkan Aktiviti Utama",
		"contributetitle" => "Menyumbang",
		"own" => "Memiliki",
		"contribute" => "Menyumbang",
		"okr" => "OKR",
		"home" => "Laman Utama",
		"no" => "Tidak",
		"add" => "Tambah",
		"delete" => "Padam",
		"update" => "Kemas Kini",
		"edit" => "Edit",
		"cancel" => "Batal",
		"submit" => "Hantar",
		"create" => "Cipta",
		"week" => "Minggu",
		"submitat" => "Hantar kepada",
		"status" => "Status",
		"action" => "Tindakan",
		"leader" => "Ketua",
		"type" => "Jenis",
		"name" => "Nama Penuh",
		"email" => "Emel",
		"jobposition" => "Jawatan Kerja",
		"role" => "Peranan",
		"timeframe" => "Tempoh",
		"progress" => "Kemajuan",
		"membership" => "Keahlian",
		"view" => "Lihat",
		"startdate" => "Tarikh Mula",
		"enddate" => "Tarikh Akhir",
		"next" => "Seterusnya",
		"previous" => "Sebelumnya",
		"profile" => "Profil",
		"firstname" => "Nama Pertama",
		"lastname" => "Nama Terakhir",
		"changepassword" => "Tukar Kata Laluan",
		"noobjectivefound" => "Tiada OKR",
		"noobjectivefoundexplain" => "Anda belum mencipta sebarang OKR untuk Tempoh Masa ini",
		"nokeyresultfound" => "Tiada Keputusan Utama",
		"nokeyresultfoundexplain" => "Anda belum mencipta sebarang Keputusan Utama untuk Objektif ini",
		"noalignobjective" => "Tiada Jajaran Objektif Ditemui",
		"noalignobjectiveexplain" => "Tiada Objektif yang jajar kepada Objektif ini",
		"noactivityfound" => "Tiada Aktiviti",
		"noactivityfoundexplain" => "Anda belum mencipta sebarang Aktiviti untuk Keputusan Utama ini",
		"objectivetitle" => "Objektif",
		"alignobjectivetitle" => "Menyumbang",
		"keyresulttitle" => "Keputusan Utama",
		"keyresultshort" => "KR",
		"activitytitle" => "Aktiviti",
		"activityshort" => "Act",
		"report" => "Laporan",
		"excellent" => "Cemerlang",
		"ontrack" => "Atas Landasan",
		"notstart" => "Belum Mula",
		"lagging" => "Lambat",
		"danger" => "Bahaya",
		"reportsubmitted" => "Laporan Telah Hantar",
		"reportsubmittedexplain" => "Anda telah Hantar Laporan untuk Minggu ini:",
		"reportnotsubmitted" => "Laporan Belum Hantar",
		"reportnotsubmittedexplain" => "Anda belum Hantar Laporan untuk Minggu ini:",
		"nocompanyfound" => "Tiada Syarikat",
		"nocompanyfoundexplain" => "Anda Belum Mencipta Syarikat",
		"nogroupfound" => "Tiada Kumpulan",
		"nogroupfoundexplain" => "Anda Belum Mencipta Kumpulan",
		"nouserfound" => "Tiada Kakitangan",
		"nouserfoundexplain" => "Anda Belum Mencipta Kakitangan",
		"notimeframefound" => "Tiada Tempoh Masa",
		"notimeframefoundexplain" => "Anda Belum Mencipta Tempoh",
		"nologfound" => "Tiada Logs",
		"nologfoundexplain" => "Tiada logs untuk Objektif ini",
		"group" => "Kumpulan",
		"personal" => "Peribadi",
		"people" => "Orang",
		"engagementrate" => "Kadar Pertunangan",
		"last30days" => "30 hari lepas",
		"last60days" => "60 hari lepas",
		"last90days" => "90 hari lepas",
		"okrhealth" => "Kesihantan OKR",
		//navbar
		"dashboard" => "Papan Pemuka",
		"yourokr" => "OKR kamu",
		"weeklyreport" => "Laporan Mingguan",
		"corporate" => "Korporat",
		"companies" => "Semua Syarikat",
		"company" => "Syarikat",
		"groups" => "Semua Kumpulan",
		"users" => "Semua Kakitangan",
		"user" => "Kakitangan",
		"okrs" => "Semua OKR",
		"alignment" => "Kejajaran",
		//topbar
		"admindashboard" => "Papan Pemuka Admin",
		"supervisordashboard" => "Supervisor Dashboard",
		"personalsetting" => "Papan Pemuka Penyelia",
		"logout" => "Log Keluar",
		//home-dashboard
		"yourplanforweek" => "Pelan kamu pada minggu ini",
		"done" => "Selesai",
		"inprogress" => "Masih Dijalankan",
		"stuck" => "Tersangkut",
		"issue" => "Masalah",
		"calendar" => "Kalendar",
		"objective" => "Objektif",
		//home-yourokr
		"objectivestatusexcellent" => "Tahniah kerana mencapai matlamat anda",
		"objectivestatusontrack" => "Lebih sebanyak ",
		"objectivestatusnotstart" => "Tempoh Masa Belum Mula Lagi",
		"objectivestatusontrack2" => "Atas Landasan",
		"objectivestatuslagging" => "Lambat sebanyak ",
		"objectivestatusdanger" => "Lambat terlampau sebanyak ",
		"keyresultexcellent" => "Tahniah kerana mencapai Keputusan Utama anda",
		"activityexcellent" => "Tahniah kerana mencapai Aktiviti anda",

		"successaddactivity" => "Anda telah berjaya menambah Aktiviti",
		"successaddactivityexplain" => "Apakah langkah yang seterusnya?",
		"successaddactivitybutton" => "Tambah lebih Aktiviti",

		"deleteactivity" => "Adakah anda pasti mahu memadam Aktiviti ini?",
		"successdeleteactivity" => "Anda telah berjaya memadam Aktiviti",

		"successeditactivity" => "Anda telah berjaya edit Aktiviti",

		"successupdateactivity" => "Anda telah berjaya mengemas kini Aktiviti",

		"successaddcompany" => "Anda telah berjaya menambah Syarikat",
		"successaddcompanyexplain" => "Apakah langkah yang seterusnya?",
		"successaddcompanybutton" => "Tambah Lebih Syarikat",

		"successeditcompany" => "Anda telah berjaya edit Syarikat",

		"deletecompany" => "Adakah anda pasti mahu memadam Syarikat ini?",
		"successdeletecompany" => "Anda telah berjaya memadam Syarikat",

		"successeditcorporate" => "Anda telah berjaya edit Korporat",

		"successaddgroup" => "Anda telah berjaya menambah Kumpulan",
		"successaddgroupexplain" => "Apakah langkah yang seterusnya?",
		"successaddgroupbutton" => "Tambah Lebih Kumpulan",

		"deletegroup" => "Adakah anda pasti mahu memadam Kumpulan ini?",
		"successdeletegroup" => "Anda telah berjaya memadam Kumpulan",

		"successeditgroup" => "Anda telah berjaya edit Kumpulan",

		"successaddkeyresult" => "Anda telah berjaya menambah Keputusan Utama",
		"successaddkeyresultexplain" => "Apakah langkah yang seterusnya?",
		"successaddkeyresultbutton" => "Tambah Lebih Keputusan Utama",

		"deletekeyresult" => "Adakah anda pasti mahu memadam Keputusan Utama ini?",
		"deletekeyresultexplain" => "Perhatikan bahawa <i> Aktiviti </i> di bawah ini <b> Keputusan Utama </b> juga akan dipadamkan.",
		"successdeletekeyresult" => "Anda telah berjaya memadam Keputusan Utama",

		"successeditkeyresult" => "Anda telah berjaya edit Keputusan Utama",

		"successupdatekeyresult" => "Anda telah berjaya mengemas kini Keputusan Utama",

		"successaddobjective" => "Anda telah berjaya menambah Objektif",
		"successaddobjectiveexplain" => "Apakah langkah yang seterusnya?",
		"successaddobjectivebutton" => "Tambah Lebih Objektif",
		"successaddobjectivebutton2" => "Tambah Lebih Keputusan Utama",

		"successeditobjective" => "Anda telah berjaya edit Objektif",

		"deleteobjective" => "Adakah anda pasti mahu memadam Objektif ini?",
		"deleteobjectiveexplain" => "Perhatikan bahawa <i> Keputusan Utama </i> di bawah ini <b> Objektif </b> juga akan dipadamkan.",
		"successdeleteobjective" => "Anda telah berjaya memadam Objektif",

		"successaddplan" => "Anda telah berjaya menambah Pelan",
		"successaddplanexplain" => "Apakah langkah yang seterusnya?",
		"successaddplanbutton" => "Tambah lebih Pelan",

		"successupdateplan" => "Anda telah berjaya mengemas kini Pelan",

		"deleteplan" => "Adakah anda pasti mahu memadam Pelan ini?",
		"successdeleteplan" => "Anda telah berjaya memadam Pelan",

		"successsubmitreport" => "Anda telah berjaya menghantar Laporan Migguan",

		"successevaluatereport" => "Anda telah berjaya menilai Laporan Migguan",

		"successaddtimeframe" => "Anda telah berjaya menambah Tempoh Masa",
		"successaddtimeframeexplain" => "Apakah langkah yang seterusnya?",
		"successaddtimeframebutton" => "Tambah Lebih Tempoh Masa",

		"successedittimeframe" => "Anda telah berjaya edit Tempoh Masa",

		"deletetimeframe" => "Adakah anda pasti mahu memadam Tempoh Masa ini?",
		"deletetimeframeexplain" => "Perhatikan bahawa <i> OKR </i> di bawah ini <b> Tempoh Masa </b> juga akan dipadamkan.",
		"successdeletetimeframe" => "Anda telah berjaya memadam Tempoh Masa",

		"reachmaxnumofuser" => "Anda telah mencapai maksimum pengguna",
		"reachmaxnumofuserexplain" => "Hubungi Kami untuk meningkatkan bilangan pengguna",

		"successadduser" => "Anda telah berjaya menambah pengguna",
		"successadduserexplain" => "Apakah langkah yang seterusnya?",
		"successadduserbutton" => "Tambah Lebih Pengguna",

		"deleteuser" => "Adakah anda pasti mahu memadam Pengguna ini?",
		"successdeleteuser" => "Anda telah berjaya memadam Pengguna",

		"successedituser" => "Anda telah berjaya edit Pengguna",

		"notsubmitreport" => "Tiada Laporan Dihantar",
		"notsubmitreportexplain" => "Kakitangan anda tidak mengemukakan sebarang laporan",

		"nookrsfoundfor" => "Tiada OKR untuk",
		"notcreateokr" => "Anda belum lagi mecipta OKR"
	];
?>