<?php
	$array = 
	[
		"viewmoreoption" => "Click to view more options",
		"viewda" => "Click to Add Doer Action",
		"viewcda" => "Click to view or close Doer Action",
		"viewkr" => "Click to Add Key Result",
		"viewckr" => "Click to View Contribute OKR",
		"viewcollapse" => "Click to collapse or show",
		"committed" => "Committed",
		"aspirational" => "Aspirational",
		"toplevel" => "Top Level",
		"reportsubmit" => "Report Submitted",
		"reportnotsubmit" => "Report Not Submitted",
		"reportreview" => "Report Review",
		"reportnotreview" => "Report Not Review",
		"totalobjective" => "Total Objectives",
		"howmany" => "How many objectives created in this Timeframe",
		"loginrate" => "Login Rate",
		"updaterate" => "Update Rate",
		"currentprogress" => "Current Progress",
		"togo" => "To Go",
		"expected" => "Expected",
		"supervisor" => "Supervisor",
		"admin" => "Admin",
		"chief" => "Chief",
		"superior" => "Superior",
		"manager" => "Manager",
		"evaluate" => "Evaluate",
		"progressremarks" => "Progress's Remarks",
		"problemremarks" => "Problem's Remarks",
		"nextweekplanremarks" => "Next week Plan Remarks",
		"problem" => "Problem",
		"nextweekplan" => "Next Week Plan",
		"plan" => "Plan",
		"draft" => "Draft",
		"department" => "Department",
		"team" => "Team",
		"project" => "Project",
		"campaign" => "Campaign",
		"optional" => "optional",
		"active" => "Active",
		"notactive" => "Not Active",
		"description" => "Description",
		"marksas" => "Marks as ",
		"unit" => "Unit",
		"percentage" => "Percentage",
		"currency" => "Currency",
		"metric" => "Metric",
		"startvalue" => "Start Value",
		"endvalue" => "End Value",
		"new" => "New",
		"okrlogs" => "OKR Logs",
		"alignto" => "Align to",
		"owner" => "Owner",
		"overallprogress" => "Overall Progress",
		"progresstimeline" => "Progress Timeline",
		"keyactivity" => "Doer Action",
		"showkeyactivity" => "Show <b>Doer</b> Action",
		"contributetitle" => "contribute",
		"own" => "own",
		"contribute" => "Contribute",
		"okr" => "OKR",
		"home" => "Home",
		"no" => "No",
		"add" => "Add",
		"delete" => "Delete",
		"update" => "Update",
		"edit" => "Edit",
		"cancel" => "Cancel",
		"submit" => "Submit",
		"create" => "Create",
		"week" => "Week",
		"submitat" => "Submit at",
		"status" => "Status",
		"action" => "Action",
		"leader" => "Leader",
		"type" => "Type",
		"name" => "Full Name",
		"email" => "Email",
		"jobposition" => "Job Position",
		"role" => "Roles",
		"timeframe" => "Timeframe",
		"progress" => "Progress",
		"membership" => "Membership",
		"view" => "View",
		"startdate" => "Start Date",
		"enddate" => "End Date",
		"next" => "Next",
		"previous" => "Previous",
		"profile" => "Profile",
		"firstname" => "First Name",
		"lastname" => "Last Name",
		"changepassword" => "Change Password",
		"noobjectivefound" => "No OKR founds",
		"noobjectivefoundexplain" => "You haven't create any OKR for this Timeframe",
		"nokeyresultfound" => "No Key Result founds",
		"nokeyresultfoundexplain" => "You haven't create any Key Result for this Objective",
		"noalignobjective" => "No Align Objective founds",
		"noalignobjectiveexplain" => "No Objective are align to this Objective",
		"noactivityfound" => "No Doer Action founds",
		"noactivityfoundexplain" => "You haven't create any Doer Action for Key Result",
		"objectivetitle" => "Objective",
		"alignobjectivetitle" => "Contribute",
		"keyresulttitle" => "Key Result",
		"keyresultshort" => "KR",
		"activitytitle" => "Action",
		"activityshort" => "DA",
		"report" => "Report",
		"excellent" => "Excellent",
		"ontrack" => "On-track",
		"notstart" => "Not Start",
		"lagging" => "Lagging",
		"danger" => "Danger",
		"reportsubmitted" => "Report Submitted",
		"reportsubmittedexplain" => "You have submitted the report for this week:",
		"reportnotsubmitted" => "No Report Submitted",
		"reportnotsubmittedexplain" => "You haven't submit any report for this week:",
		"nocompanyfound" => "No Company founds",
		"nocompanyfoundexplain" => "You haven't create any Company",
		"nogroupfound" => "No Group founds",
		"nogroupfoundexplain" => "You haven't create any Group",
		"nouserfound" => "No Users founds",
		"nouserfoundexplain" => "You haven't create any User",
		"notimeframefound" => "No Timeframe founds",
		"notimeframefoundexplain" => "You haven't create any timeframe. Add your custom timeframe that suit your organization",
		"nologfound" => "No logs found",
		"nologfoundexplain" => "There is no logs for this Objective",
		"group" => "Group",
		"personal" => "Personal",
		"people" => "People",
		"engagementrate" => "Engagement Rate",
		"last30days" => "last 30 days",
		"last60days" => "last 60 days",
		"last90days" => "last 90 days",
		"okrhealth" => "OKR Health",
		//navbar
		"dashboard" => "Dashboard",
		"yourokr" => "Your OKR",
		"weeklyreport" => "PPP & 1-to-1",
		"corporate" => "Corporate",
		"companies" => "Companies",
		"company" => "Company",
		"groups" => "Groups",
		"users" => "Users",
		"user" => "User",
		"okrs" => "OKRs",
		"alignment" => "Alignment",
		//topbar
		"admindashboard" => "Admin Dashboard",
		"supervisordashboard" => "Supervisor Dashboard",
		"personalsetting" => "Personal Settings",
		"logout" => "Logout",
		//home-dashboard
		"yourplanforweek" => "Your Plan for Week",
		"done" => "Done",
		"inprogress" => "In Progress",
		"stuck" => "Stuck",
		"issue" => "Issue",
		"calendar" => "<b>Doer</b> Calendar",
		"objective" => "Objective",
		//home-yourokr
		"objectivestatusexcellent" => "Congrats for achieve your goal",
		"objectivestatusontrack" => "Ahead by ",
		"objectivestatusnotstart" => "Timeframe Not Start yet",
		"objectivestatusontrack2" => "On-track",
		"objectivestatuslagging" => "Lagging by ",
		"objectivestatusdanger" => "Lagging too much by ",
		"keyresultexcellent" => "Congrats for achieve your Key Result",
		"activityexcellent" => "Congrats for achieve your Doer Action",

		"successaddactivity" => "You have successfully added an Doer Action",
		"successaddactivityexplain" => "What's your next step?",
		"successaddactivitybutton" => "Add More Doer Action",

		"deleteactivity" => "Are you sure you want to delete this Doer Action?",
		"successdeleteactivity" => "You have successfully Delete an Doer Action",

		"successeditactivity" => "You have successfully edit an Doer Action",

		"successupdateactivity" => "You have successfully Update an Doer Action",

		"successaddcompany" => "You have successfully added a Company",
		"successaddcompanyexplain" => "What's your next step?",
		"successaddcompanybutton" => "Add More Company",

		"successeditcompany" => "You have successfully edit a Company",

		"deletecompany" => "Are you sure you want to delete this Company?",
		"successdeletecompany" => "You have successfully Delete a Company",

		"successeditcorporate" => "You have successfully edit a Corporate",

		"successaddgroup" => "You have successfully added a Group",
		"successaddgroupexplain" => "What's your next step?",
		"successaddgroupbutton" => "Add More Group",

		"deletegroup" => "Are you sure you want to remove this Group?",
		"successdeletegroup" => "You have successfully Delete a Group",

		"successeditgroup" => "You have successfully edit a Group",

		"successaddkeyresult" => "You have successfully added a Key Result",
		"successaddkeyresultexplain" => "What's your next step?",
		"successaddkeyresultbutton" => "Add More Key Result",

		"deletekeyresult" => "Are you sure you want to delete this Key Result?",
		"deletekeyresultexplain" => "Just note that the <i>Doer Action</i> under this <b>Key Result</b> will also delete.",
		"successdeletekeyresult" => "You have successfully Delete a Key result",

		"successeditkeyresult" => "You have successfully edit a Key Result",

		"successupdatekeyresult" => "You have successfully Update a Key Result",

		"successaddobjective" => "You have successfully added an Objective",
		"successaddobjectiveexplain" => "What's your next step?",
		"successaddobjectivebutton" => "Add More Objective",
		"successaddobjectivebutton2" => "Add Key Result",

		"successeditobjective" => "You have successfully edit a Objective",

		"deleteobjective" => "Are you sure you want to delete this Objective?",
		"deleteobjectiveexplain" => "Just note that the <i>Key Result</i> under this <b>Objective</b> will also delete.",
		"successdeleteobjective" => "You have successfully Delete a Objective",

		"successaddplan" => "You have successfully added a Plan",
		"successaddplanexplain" => "What's your next step?",
		"successaddplanbutton" => "Add More Plan",

		"successupdateplan" => "You have successfully updated the Plan",

		"deleteplan" => "Are you sure you want to delete this Plan?",
		"successdeleteplan" => "You have successfully Delete a Plan",

		"successsubmitreport" => "You have successfully submitted Weekly Report",

		"successevaluatereport" => "You have successfully evaluated Weekly Report",

		"successaddtimeframe" => "You have successfully added a Timeframe",
		"successaddtimeframeexplain" => "What's your next step?",
		"successaddtimeframebutton" => "Add More Timeframe",

		"successedittimeframe" => "You have successfully edit a Timeframe",

		"deletetimeframe" => "Are you sure you want to delete this Timeframe?",
		"deletetimeframeexplain" => "Just note that the <i>Plan</i> under this <b>Timeframe</b> will also delete.",
		"successdeletetimeframe" => "You have successfully Delete a Timeframe",

		"reachmaxnumofuser" => "You have reach the maximum of user",
		"reachmaxnumofuserexplain" => "Contact Us for increasing the number of user",

		"successadduser" => "You have successfully added a User",
		"successadduserexplain" => "What's your next step?",
		"successadduserbutton" => "Add More User",

		"deleteuser" => "Are you sure you want to delete this User?",
		"successdeleteuser" => "You have successfully Delete a User",

		"successedituser" => "You have successfully edit a User",

		"notsubmitreport" => "No Report Submited",
		"notsubmitreportexplain" => "Your underlings not submit any report",

		"nookrsfoundfor" => "No OKR founds for",
		"notcreateokr" => "You haven't create any OKR"
	];
?>