<?php
	$array = 
	[
		"viewmoreoption" => "点击查看更多选项",
		"viewda" => "点击添加 Doer 行动",
		"viewcda" => "点击查看或关闭 Doer 行动",
		"viewkr" => "单击以添加关键结果",
		"viewckr" => "点击查看贡献 OKR",
		"viewcollapse" => "单击以折叠或显示",
		"committed" => "承诺",
		"aspirational" => "抱负",
		"toplevel" => "顶层",
		"reportsubmit" => "已提交报告",
		"reportnotsubmit" => "还没提交报告",
		"reportreview" => "已评论报告",
		"reportnotreview" => "还没评论报告",
		"totalobjective" => "总目的",
		"howmany" => "在此时间范围内创建了多少个目的",
		"loginrate" => "登录率",
		"updaterate" => "更新率",
		"currentprogress" => "目前的进展",
		"togo" => "剩下",
		"expected" => "预期",
		"supervisor" => "主管",
		"admin" => "管理员",
		"chief" => "首席",
		"superior" => "优越",
		"manager" => "经理",
		"evaluate" => "评估",
		"progressremarks" => "进度的评论",
		"problemremarks" => "难题的评论",
		"nextweekplanremarks" => "下周计划的评论",
		"problem" => "难题",
		"nextweekplan" => "下周计划",
		"plan" => "计划",
		"draft" => "草案",
		"department" => "部门",
		"team" => "团队",
		"project" => "项目",
		"campaign" => "暂时活动",
		"optional" => "可选",
		"active" => "活跃",
		"notactive" => "不活跃",
		"description" => "描述",
		"marksas" => "标记为", 
		"unit" => "单元",
		"percentage" => "百分比",
		"currency" => "货币",
		"metric" => "测量",
		"startvalue" => "起始值",
		"endvalue" => "终值",
		"new" => "新",
		"okrlogs" => "日志",
		"alignto" => "对齐",
		"owner" => "所有者",
		"overallprogress" => "总体进程",
		"progresstimeline" => "进步行为",
		"keyactivity" => "关键活动",
		"showkeyactivity" => "显示关键活动",
		"contributetitle" => "助于",
		"own" => "拥有",
		"contribute" => "由贡献",
		"okr" => "目的和关键结果章节",
		"home" => "主页",
		"no" => "没有",
		"add" => "加",
		"delete" => "删除",
		"update" => "更新",
		"edit" => "编辑",
		"submit" => "提交",
		"create" => " 创造",
		"cancel" => "取消",
		"week" => "周",
		"submitat" => "提交于",
		"status" => "状态",
		"action" => "行动",
		"leader" => "领导",
		"type" => "类型",
		"name" => "全名",
		"email" => "电子邮件",
		"jobposition" => "工作职位",
		"role" => "角色",
		"timeframe" => "大体时间",
		"progress" => "进度",
		"membership" => "成员",
		"view" => "视图",
		"startdate" => "开始日期",
		"enddate" => "结束日期",
		"next" => "下周",
		"previous" => "上周",
		"profile" => "侧面",
		"firstname" => "名字",
		"lastname" => "姓",
		"changepassword" => "更改密码",
		"noobjectivefound" => "没有创造目的和关键结果",
		"noobjectivefoundexplain" => "您还没有在任何大体时间创造目的和关键结果",
		"nokeyresultfound" => "没有创造关键结果",
		"nokeyresultfoundexplain" => "您还没有为了这目的创造关键结果",
		"noalignobjective" => "没有创造对齐目的",
		"noalignobjectiveexplain" => "这个目的没有被其他目的对齐",
		"noactivityfound" => "没有创造活动",
		"noactivityfoundexplain" => "您还没有为了这关键结果创造活动",
		"objectivetitle" => "目的",
		"alignobjectivetitle" => "助于",
		"keyresulttitle" => "关键结果",
		"keyresultshort" => "KR",
		"activitytitle" => "活动",
		"activityshort" => "Act",
		"report" => "报告",
		"excellent" => "优秀",
		"ontrack" => "步入正轨",
		"notstart" => "还没开始",
		"lagging" => "落后",
		"danger" => "危险",
		"reportsubmitted" => "报告已提交",
		"reportsubmittedexplain" => "您已经提交了本周的报告:",
		"reportnotsubmitted" => "没有报告提交",
		"reportnotsubmittedexplain" => "您本周未提交任何报告:",
		"nocompanyfound" => "没有创造公司",
		"nocompanyfoundexplain" => "您尚未创建任何公司",
		"nogroupfound" => "没有创造部门",
		"nogroupfoundexplain" => "您尚未创建任何部门",
		"nouserfound" => "没有创造员工帐户",
		"nouserfoundexplain" => "您尚未创建任何员工帐户",
		"notimeframefound" => "没有创造大体时间",
		"notimeframefoundexplain" => "您尚未创建任何大体时间",
		"nologfound" => "没有创造日志",
		"nologfoundexplain" => "您尚未创建任何日志",
		"group" => "部门",
		"personal" => "个人",
		"people" => "人",
		"engagementrate" => "参与率",
		"last30days" => "最近30天",
		"last60days" => "最近60天",
		"last90days" => "最近90天",
		"okrhealth" => "目的和关键结果的健康",
		//navbar
		"dashboard" => "仪表板",
		"yourokr" => "您的目的和关键结果",
		"weeklyreport" => "每周报告",
		"corporate" => "企业",
		"companies" => "全公司",
		"company" => "公司",
		"groups" => "全部门",
		"users" => "全员工",
		"user" => "员工",
		"okrs" => "全目的和关键结果",
		"alignment" => "对齐目的结构体",
		//topbar
		"admindashboard" => "管理仪表板",
		"supervisordashboard" => "主管仪表板",
		"personalsetting" => "个人设定",
		"logout" => "登出",
		//home-dashboard
		"yourplanforweek" => "您的计划周",
		"done" => "做完",
		"inprogress" => "进行中",
		"stuck" => "卡住",
		"issue" => "问题",
		"calendar" => "日历",
		"objective" => "目的",
		//home-yourokr
		"objectivestatusexcellent" => "恭喜您达成目标",
		"objectivestatusontrack" => "先 ",
		"objectivestatusnotstart" => "时间表尚未开始",
		"objectivestatusontrack2" => "步入正轨",
		"objectivestatuslagging" => "落后 ",
		"objectivestatusdanger" => "滞后太多 ",
		"keyresultexcellent" => "恭喜您达成关键成果",
		"activityexcellent" => "恭喜您达成活动",

		"successaddactivity" => "您已成功添加活动",
		"successaddactivityexplain" => "下一步是什么？",
		"successaddactivitybutton" => "添加更多活动",


		"deleteactivity" => "您确定要删除此活动吗？",
		"successdeleteactivity" => "您已成功删除活动",
		
		"successeditactivity" => "您已成功编辑活动",
		"successupdateactivity" => "您已成功更新活动进度",

		"successaddcompany" => "您已成功添加公司",
		"successaddcompanyexplain" => "下一步是什么？",
		"successaddcompanybutton" => "添加更多公司",

		"successeditcompany" => "您已成功编辑公司",
		"deletecompany" => "您确定要删除该公司吗？",
		"successdeletecompany" => "您已成功删除公司",

		"successeditcorporate" => "您已成功编辑企业",

		"successaddgroup" => "您已成功添加部门",
		"successaddgroupexplain" => "下一步是什么？",
		"successaddgroupbutton" => "添加更多部门",

		"deletegroup" => "您确定要删除该部门吗？",
		"successdeletegroup" => "您已成功删除部门",

		"successeditgroup" => "您已成功编辑部门",

		"successaddkeyresult" => "您已成功添加关键结果",
		"successaddkeyresultexplain" => "下一步是什么？",
		"successaddkeyresultbutton" => "添加更多关键结果",

		"deletekeyresult" => "您确定要删除该关键结果吗？",
		"deletekeyresultexplain" => "请注意，此<b>关键结果</b>下的<i>活动</i>也将删除。",
		"successdeletekeyresult" => "您已成功删除关键结果",

		"successeditkeyresult" => "您已成功编辑关键结果",

		"successupdatekeyresult" => "您已成功更新关键结果进度",

		"successaddobjective" => "您已成功添加目的",
		"successaddobjectiveexplain" => "下一步是什么？",
		"successaddobjectivebutton" => "添加更多目的",
		"successaddobjectivebutton2" => "添加关键结果",

		"successeditobjective" => "您已成功编辑目的",

		"deletekeyresult" => "您确定要删除该目的吗？",
		"deletekeyresultexplain" => "请注意，此<b>目的</b>下的<i>关键结果</i>也将删除。",
		"successdeletekeyresult" => "您已成功删除目的",

		"successaddplan" => "您已成功添加计划",
		"successaddplanexplain" => "下一步是什么？",
		"successaddplanbutton" => "添加更多计划",

		"successupdateplan" => "您已成功更新计划进度",

		"deleteplan" => "您确定要删除该计划吗？",
		"successdeleteplan" => "您已成功删除计划",

		"successsubmitreport" => "您已成功提交每周报告",

		"successevaluatereport" => "您已成功评估报告",

		"successaddtimeframe" => "您已成功添加大体时间",
		"successaddtimeframeexplain" => "下一步是什么？",
		"successaddtimeframebutton" => "添加更多大体时间",

		"successedittimeframe" => "您已成功编辑大体时间",

		"deletetimeframe" => "您确定要删除该大体时间吗？",
		"deletetimeframeexplain" => "请注意，此<b>大体时间</b>下的<i>目的</i>也将删除。",
		"successdeletetiemframe" => "您已成功删除大体时间",

		"reachmaxnumofuser" => "您已达到用户数上限",
		"reachmaxnumofuserexplain" => "联系我们以增加用户数量",

		"successadduser" => "您已成功添加员工",
		"successadduserexplain" => "下一步是什么？",
		"successadduserbutton" => "添加更多员工",

		"deleteuser" => "您确定要删除该员工吗？",
		"successdeleteuser" => "您已成功删除员工",

		"successedituser" => "您已成功编辑员工",

		"notsubmitreport" => "没有报告提交",
		"notsubmitreportexplain" => "您的下属未提交任何报告",

		"nookrsfoundfor" => "没有创造目的和关键结果给",
		"notcreateokr" => "您尚未创建任何目的和关键结"

	];
?>